### ISSUE TITLE
program takes to long to exit

### ISSUE THREAD

**Issue by TF08** [ritchielawrence/mtee#1]
Hello Ritchie , thank you for mTee!

I'm using it (V 2.1) in Windows 7x64 without any problems in many scripts.

Now I tried to do it (V 2.2) with Windows10x64 Pro (Version 10.0.10586) and had to stop using it.
It seems to have the bug you are fixed already: program takes to long to exit.

Hope for your help.
Thomas

**Comment by ritchielawrence** [comment]
Hi Thomas,

I'm unable to replicate this issue with mtee v2.2 on Windows 10x64 Pro Version 1511 (OS Build 10586.446), I ran:-

``` batch
dir | mtee
```

And mtee exited immediately. Is it possible you have an older version of mtee on your machine? Maybe in a directory that's in your PATH environment variable, and the version being executed isn't the one you expected? Can you detail exactly how I can replicate?

Thanks.

**Comment by TF08** [comment]
Hi Ritchie,
I'm right now on vacation and have no access to my environment.
When I'm back (08/2016), I'll give a better report.
But: I used version 2.2 - mtee /? shows:
"MTEE v2.2 Win32 Commandline Standard Stream Splitter for NT4 .. Windows 10.
Copyright (c) 2001-2016 Ritchie Lawrence, http://www.commandline.co.uk."

So long
Thomas

**Comment by TF08** [comment]
Hi Ritchie,
back from vacation first thing I checked was mtee ...
I guest I did the mistake: I use mtee (see below) unqualified in my scripts. So I refered the path with the old version 2.1 which is very slow under Windows 10.

Sorry for false report & thank you again for mtee!

`setlocal EnableDelayedExpansion
...
set LOG_FILE_NAME=%~n0
set LOG_STRING=mtee.exe /T /+ "!LOG_FILE_NAME!"
rem -- MYTOOL_PATH includes the directory with mtee.exe
set PATH=!MYTOOL_PATH!;%PATH%

... -- example how I use mtee.exe:
echo -=#=-=#=-=#=-=#=-=#=-%DATE% %TIME:~0,8%-=#=-=#=-=#=-=#=-| %LOG_STRING%
echo --- END - Subroutine [SUB_WATCH_DOG] --- | %LOG_STRING%
echo -=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-| %LOG_STRING%`
