### ISSUE TITLE
mtee /E /D /T randomly exits with exit-code 1

### ISSUE THREAD

**Issue by dukeglukem** [ritchielawrence/mtee#2]
In some cases I have a problem when using following command:
`<process> 2>&1 | mtee.exe /E /D /T %temp%\process.log`
My piped process always exits with 0, but in 10-15% cases mtee exits with exit-code 1, which is not correct.

If I am using mtee without /D /T flags, then mtee always exits with correct exit code.

**Comment by dukeglukem** [comment]
Looks like issue is in something else, since I cannot reproduce it using command above. Actually command has more applications (vmrun, Elevate64, cmd), so the problem may cause other application:

```
vmrun.exe -gu "%guest_user%" -gp "%guest_pass%" runScriptInGuest "!vmx!" -activeWindow -interactive "" "%%temp%%\Elevate64.exe -w -- %%WinDir%%\System32\cmd.exe /c ""%%temp%%\process.bat 2^>^&1 ^| %%temp%%\mtee.exe /E /D /T %%temp%%\process.log"""
echo %errorLevel%
```

**Comment by ritchielawrence** [comment]
Hi dukeglukem, thanks for the update and closing the issue.
