### ISSUE TITLE
Problem with logging console messages of Tesseract

### ISSUE THREAD

**Issue by kpsbahn** [ritchielawrence/mtee#7]
This seems to be a very peculiar problem.
**mtee** works very well in all the tests that I did but it fails to log a particular set of console messages from **Tesseract**,
Needless to say, **Tesseract** is an OCR software that extracts text from image. 

A typical command is
`tesseract files.txt ocred`
files.txt is a list of PNG files to be processed.
"ocred" is the name of the output file.
Tesseract will process each image file listed files.txt one by one and create ocred.txt containing the OCRed text

Processing each file takes around 10 seconds and it keeps throwing out console messages like 
Page 0 : 000.png
Page 1 : 001.png
Page 2 : 002.png   as and when a file is processed. 

**I want to watch the progress and also capture those messages to a log file.**
mtee appeared to be the ideal solution.
But, for some strange reason, this command fails.
`tesseract files.txt ocred | mtee log.txt  `     

I can see the messages on console. But log.txt is not written. The file size shows zero.
Even more strange, there is no problem with the following command, where Tesseract outputs the standard help message.
`tesseract | mtee log.txt`  

I do understand this is really not an issue with mtee, because it works well in all other cases.
But I still felt it is better that I bring it to your notice for investigation and possible solution.

Regards,

**Comment by andry81** [comment]
Does the utility print it to the stderr? Try this one:
```
tesseract files.txt ocred 2>&1 | mtee log.txt
```

**Comment by kpsbahn** [comment]
> 
> 
> Does the utility print it to the stderr? Try this one:
> 
> ```
> tesseract files.txt ocred 2>&1 | mtee log.txt
> ```

Thank you.
I tried your suggestion.
Now the log file is created but the console message comes after the entire operation is over.
I want to see the progress; as and when a file is processed.
That wait period is excruciating; not knowing if something is happening or not.

Regards,

**Comment by andry81** [comment]
> I want to see the progress; as and when a file is processed.

It depends on the `tesseract` utility output buffering. Basically a pipe write process should call to a flush function to push data from an internal buffer to a pipe end. If an utility does not do that, then a buffer get flushed either when there is no any space in a buffer or when the process get closed. So it does not depend on `mtee` utilty or any other utility on the end side of a pipe channel. This is one of the reason to not to use the shell piping at all because it has a poor control at very beginning.

**Comment by kpsbahn** [comment]
Thank you.
I suppose we have to leave it at that. and close this issue

Regards,
